name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      # Step 4: Lint code
      - name: Lint
        run: flake8 .

      # Step 5: Run tests with PYTHONPATH set to project root
      - name: Run Tests
        run: |
          echo "Running tests with PYTHONPATH set to project root..."
          export PYTHONPATH="${PYTHONPATH}:$PWD"
          pytest -q --disable-warnings --maxfail=1
